### ISSUE TITLE
Large(ish) cases don't work with current driver@main

### ISSUE THREAD

**Issue by MTCam** [illinois-ceesd/drivers_y3-prediction#19]
Scalability case on 128 ranks have started to fail with current driver@main.  Before recent changes, the code ran up to 512 ranks without issue.  Only the 128 rank case fails with this error.  512 has not been tested since this trouble started.

more details will follow, just want to get this on the radar.

```
2023-04-17 07:11:35,502 - INFO - meshmode.array_context - Array Contraction: completed (135.71s wall 1.00x CPU)
2023-04-17 07:11:35,503 - INFO - arraycontext.impl.pytato.compile - transform_loopy_program for 'unfiltered_rhs': completed (355.22s wall 1.00x CPU)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/emirge/miniforge3/envs/prediction.env/lib/python3.11/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/emirge/miniforge3/envs/prediction.env/lib/python3.11/site-packages/mpi4py/run.py", line 198, in main
    run_command_line(args)
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/emirge/miniforge3/envs/prediction.env/lib/python3.11/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "driver.py", line 73, in <module>
    main(restart_filename=restart_filename, target_filename=target_filename,
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/emirge/mirgecom/mirgecom/mpi.py", line 200, in wrapped_func
    func(*args, **kwargs)
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/y3prediction/prediction.py", line 3096, in main
    advance_state(rhs=my_rhs, timestepper=timestepper,
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/emirge/mirgecom/mirgecom/steppers.py", line 439, in advance_state
    _advance_state_stepper_func(
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/emirge/mirgecom/mirgecom/steppers.py", line 164, in _advance_state_stepper_func
    state = timestepper(state=state, t=t, dt=dt, rhs=maybe_compiled_rhs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/y3prediction/prediction.py", line 608, in _compiled_stepper_wrapper
    return compiled_lsrk45_step(actx, state, t, dt, rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/emirge/grudge/grudge/shortcuts.py", line 56, in compiled_lsrk45_step
    rhs_val = f(t + c*h, y)
              ^^^^^^^^^^^^^
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/y3prediction/prediction.py", line 3078, in my_rhs
    unfiltered_rhs_compiled(t, state)
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/emirge/arraycontext/arraycontext/impl/pytato/compile.py", line 366, in __call__
    compiled_func = self._dag_to_compiled_func(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/emirge/grudge/grudge/array_context.py", line 307, in _dag_to_compiled_func
    ) = self._dag_to_transformed_pytato_prg(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/emirge/arraycontext/arraycontext/impl/pytato/compile.py", line 442, in _dag_to_transformed_pytato_prg
    .with_transformed_program(self
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/emirge/pytato/pytato/target/loopy/__init__.py", line 151, in with_transformed_program
    return self.copy(program=f(self.program))
                             ^^^^^^^^^^^^^^^
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/emirge/meshmode/meshmode/array_context.py", line 1741, in transform_loopy_program
    raise err
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/emirge/meshmode/meshmode/array_context.py", line 1738, in transform_loopy_program
    iel_to_idofs = _get_iel_to_idofs(knl)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/emirge/meshmode/meshmode/array_context.py", line 1068, in _get_iel_to_idofs
    raise NotImplementedError(f"Cannot fit loop nest '{insn.within_inames}'"
NotImplementedError: Cannot fit loop nest 'frozenset({'idof_ensm14'})' into known set of loop-nest patterns.
2023-04-17 07:11:36,495 - INFO - loopy.codegen - unfiltered_rhs: generate code: completed (16.88s wall 1.00x CPU)
2023-04-17 07:11:36,664 - INFO - loopy.schedule - unfiltered_rhs: schedule: completed (11.42s wall 1.00x CPU)
2023-04-17 07:11:37,738 - INFO - loopy.tools - contract_arrays on 'unfiltered_rhs': completed (130.51s wall 1.00x CPU)
2023-04-17 07:11:37,981 - INFO - pyopencl - build program: kernel 'unfiltered_rhs' was part of a lengthy source build resulting from a binary cache miss (6.77 s)
2023-04-17 07:11:39,042 - INFO - loopy.schedule - unfiltered_rhs: schedule: completed (10.97s wall 1.00x CPU)
2023-04-17 07:11:39,709 - INFO - loopy.codegen - unfiltered_rhs: generate code: completed (18.08s wall 1.00x CPU)
2023-04-17 07:11:39,800 - INFO - loopy.schedule - unfiltered_rhs: schedule: completed (4.37s wall 1.00x CPU)
2023-04-17 07:11:40,367 - INFO - loopy.schedule - unfiltered_rhs: schedule: completed (18.51s wall 1.00x CPU)
2023-04-17 07:11:40,484 - INFO - meshmode.array_context - Array Contraction: completed (138.73s wall 1.00x CPU)
2023-04-17 07:11:40,486 - INFO - arraycontext.impl.pytato.compile - transform_loopy_program for 'unfiltered_rhs': completed (357.87s wall 1.00x CPU)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/emirge/miniforge3/envs/prediction.env/lib/python3.11/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/emirge/miniforge3/envs/prediction.env/lib/python3.11/site-packages/mpi4py/run.py", line 198, in main
    run_command_line(args)
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/emirge/miniforge3/envs/prediction.env/lib/python3.11/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "driver.py", line 73, in <module>
    main(restart_filename=restart_filename, target_filename=target_filename,
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/emirge/mirgecom/mirgecom/mpi.py", line 200, in wrapped_func
    func(*args, **kwargs)
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/y3prediction/prediction.py", line 3096, in main
    advance_state(rhs=my_rhs, timestepper=timestepper,
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/emirge/mirgecom/mirgecom/steppers.py", line 439, in advance_state
    _advance_state_stepper_func(
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/emirge/mirgecom/mirgecom/steppers.py", line 164, in _advance_state_stepper_func
    state = timestepper(state=state, t=t, dt=dt, rhs=maybe_compiled_rhs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/y3prediction/prediction.py", line 608, in _compiled_stepper_wrapper
    return compiled_lsrk45_step(actx, state, t, dt, rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/emirge/grudge/grudge/shortcuts.py", line 56, in compiled_lsrk45_step
    rhs_val = f(t + c*h, y)
              ^^^^^^^^^^^^^
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/y3prediction/prediction.py", line 3078, in my_rhs
    unfiltered_rhs_compiled(t, state)
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/emirge/arraycontext/arraycontext/impl/pytato/compile.py", line 366, in __call__
    compiled_func = self._dag_to_compiled_func(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/emirge/grudge/grudge/array_context.py", line 307, in _dag_to_compiled_func
    ) = self._dag_to_transformed_pytato_prg(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/emirge/arraycontext/arraycontext/impl/pytato/compile.py", line 442, in _dag_to_transformed_pytato_prg
    .with_transformed_program(self
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/emirge/pytato/pytato/target/loopy/__init__.py", line 151, in with_transformed_program
    return self.copy(program=f(self.program))
                             ^^^^^^^^^^^^^^^
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/emirge/meshmode/meshmode/array_context.py", line 1741, in transform_loopy_program
    raise err
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/emirge/meshmode/meshmode/array_context.py", line 1738, in transform_loopy_program
    iel_to_idofs = _get_iel_to_idofs(knl)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/y3-prediction-testing/emirge/meshmode/meshmode/array_context.py", line 1068, in _get_iel_to_idofs
    raise NotImplementedError(f"Cannot fit loop nest '{insn.within_inames}'"
NotImplementedError: Cannot fit loop nest 'frozenset({'idof_ensm16'})' into known set of loop-nest patterns.
2023-04-17 07:11:41,867 - INFO - loopy.schedule - unfiltered_rhs: schedule: completed (11.63s wall 1.00x CPU)
2023-04-17 07:11:43,640 - INFO - loopy.tools - contract_arrays on 'unfiltered_rhs': completed (128.28s wall 1.00x CPU)
```

**Comment by ZwFink** [comment]
This is happening to me on `smoke_test_ks_3d` using 4 ranks.
````bash
  File "/usr/WS2/fink12/drivers_y3-prediction/emirge/meshmode/meshmode/array_context.py", line 1068, in _get_iel_to_idofs
    raise NotImplementedError(f"Cannot fit loop nest '{insn.within_inames}'"
NotImplementedError: Cannot fit loop nest 'frozenset({'idof_ensm2'})' into known set of loop-nest patterns.
```

Am I the only one?

**Comment by majosm** [comment]
> This is happening to me on `smoke_test_ks_3d` using 4 ranks.
> 
> ```shell
>   File "/usr/WS2/fink12/drivers_y3-prediction/emirge/meshmode/meshmode/array_context.py", line 1068, in _get_iel_to_idofs
>     raise NotImplementedError(f"Cannot fit loop nest '{insn.within_inames}'"
> NotImplementedError: Cannot fit loop nest 'frozenset({'idof_ensm2'})' into known set of loop-nest patterns.
> ```
> 
> Am I the only one?

https://github.com/illinois-ceesd/mirgecom/issues/944

A fix is still TBD. Depending on what you're doing, you may be able to avoid it by setting `use_wall: False` in `run_params.yaml`.
